reddit_clone/config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'
  get 'posts/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy]
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User
        
    has_many :post_subs,
        foreign_key: :post_id,
        class_name: :PostSub
        
    has_many :subs,
        through: :post_subs,
        source: :sub
end

reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub
    
    belongs_to :post,
        foreign_key: :post_id,
        class_name: :Post
end

reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
    belongs_to :moderator, 
    foreign_key: :moderator_id,
    class_name: :User 
    
    has_many :post_subs,
    foreign_key: :sub_id,
    class_name: :PostSub
    
    has_many :posts,
        through: :post_subs,
        source: :post
end

reddit_clone/app/models/user.rb
class User < ApplicationRecord
    validates :username, :password_digest, :session_token, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true}
    attr_reader :password 

    after_initialize :ensure_session_token
   
    # SPIRE 

    has_many :subs, 
        foreign_key: :moderator_id,
        class_name: :Sub 

     has_many :posts,
        foreign_key: :author_id,
        class_name: :Post
    

   def self.find_by_credentials(username, password)
        @user = User.find_by(username: username)

        if @user && @user.is_password?(password)
            @user 
        else
            nil 
        end
   end

   def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
   end

   def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
   end

   def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
   end

   def ensure_session_token 
        self.session_token ||= SecureRandom::urlsafe_base64
   end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #crlll
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :
  def new
    @subs = Sub.all
    @post = Post.new 
    render :new 
  end

  def edit
    @subs = Sub.all
    @post = Post.find(params[:id])
    render :edit
  end

  def show
    @post = Post.find(params[:id])
    render :show 
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id 


    if @post.save 
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages 
      render :new 
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post
      @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages 
      render :new 
    end

  end

  private 

  def post_params
    params.require(:post).permit(:title, :content, :url, :sub_id)
  end
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]

    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login!(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = ["Invalid username or password"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    def index
        @subs = Sub.all 
        render :index 
    end

    def show
        @sub = Sub.find(params[:id])
        render :show 
    end

    def create 
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def new
        @sub = Sub.new 
        render :new 
    end

    def edit 
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update 
        @sub = Sub.find(params[:id])
        if @sub
            @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new 
        render :new 
    end

    def create
        @user = User.new(user_params)

        if @user.save 
            login!(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = @user.errors.full_messages 
            render :new
        end
    end

    private 

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li> <%= current_user.username %></li>
      <li> <a href="<%= new_sub_url %>">Create a sub!</a> </li>
      <li> <a href="<%= subs_url %>">All Subs</a> </li>
      <li> 
         <% if !logged_in? %>
            <a href="<%= new_session_url %>">Sign In! 🐙</a>
            <br>
            <a href="<%= new_user_url %>">Create a user! 👶</a>
          <% else %>
            <form action="<%= session_url %>" method="POST">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="submit" value='Sign Out! 👋'>
            </form>
        <% end %>
      </li>
      
    </ul>
   

    

    <% if flash[:errors] %>
      <%= flash[:errors] %>
    <% end %>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/edit.html.erb
<h1>Edit Post!</h1>

<form action='<%= post_url(@post) %>' method='POST'>
    <input type="hidden" name="_method" value="PATCH">
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <label>Title:
    <input type='text' name='post[title]' value='<%= @post.title %>'>
  </label>
  <label>URL:
    <input type='text' name='post[url]' value='<%= @post.url %>'>
  </label>
  <br>
  <label>Content:
    <textarea name="post[content]" cols="30" rows="10" value="<%= @post.content %>"></textarea>
  </label>

  <% @subs.each_with_index do |sub, id| %>
    <br>
    <input id="<%= id.to_s %>" type="checkbox" name="post[sub_id]" 
    value="<%= sub.id %>" <%= @post.sub_id == sub.id ? "checked" : "" %>>
    <label for="<%= id.to_s %>"><%= sub.title %></label>
  <% end %>
  <br>
  <input type='submit' value='Submit Post'>
</form>

reddit_clone/app/views/posts/new.html.erb
<h1>New Post!</h1>

<form action='<%= posts_url %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <label>Title:
    <input type='text' name='post[title]' value=''>
  </label>
  <label>URL:
    <input type='text' name='post[url]' value=''>
  </label>
  <br>
  <label>Content:
    <textarea name="post[content]" cols="30" rows="10"></textarea>
  </label>

  <% @subs.each_with_index do |sub, id| %>
    <br>
    <input id="<%= id.to_s %>" type="checkbox" name="post[sub_id]" value="<%= sub.id %>">
    <label for="<%= id.to_s %>"><%= sub.title %></label>
  <% end %>
  <br>
  <input type='submit' value='Submit Post'>
</form>

reddit_clone/app/views/posts/show.html.erb
<h2><%= @post.title %> by <%= User.find(@post.author_id).username %></h2>

<h4><b>Content</b></h4>
<%= @post.content %>


<h4><b>Subs</b></h4>
<%= Sub.find(@post.sub_id).title %>
<br>



<% if current_user.id == @post.author_id %>
    <a href="<%= edit_post_url(@post) %>">Edit</a>
<% end %>

reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Your Sub!</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <label>Title:
      <input type='text' name='sub[title]' value='<%= @sub.title %>'>
    </label>

    <label>Description:
      <input type='textarea' name='sub[description]' value='<%= @sub.description %>'>
    </label>

    <input type="submit" value="Submit!">
</form>

reddit_clone/app/views/subs/index.html.erb
<h1>All the SUBS!!</h1>

<ul>
    <% @subs.each do |sub| %>
        <li>
            <a href="<%= sub_url(sub) %>">
                <%= sub.title %>
            </a>
        </li>
    <% end %>
</ul>

reddit_clone/app/views/subs/new.html.erb
<h1>Create a new SUB! </h1>

<form action="<%= subs_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label>Title:
      <input type='text' name='sub[title]' value=''>
    </label>

    <label>Description:
      <input type='textarea' name='sub[description]' value=''>
    </label>

    <input type="submit" value="Submit!">
</form>

reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h3>Description</h3>

<%= @sub.description  %> 

<a href="<%= new_post_url %>">Add a Post!</a>
<!--<form action="<%#= post_url %>" method="POST">
    <input type="hidden" name="post[sub_id]" value="<%#= @sub.id %>">
</form>-->

<ul>
    <% @sub.posts.each do |post| %>
        <li><a href="<%= post_url(post) %>"><%= post.title%></a></li>
    <% end %>
</ul>

<% if current_user.id == @sub.moderator_id %>
    <a href="<%= edit_sub_url(@sub) %>">Edit</a>
<% end %>

reddit_clone/app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Username:
      <input type='text' name='user[username]' value='<%= @user.username %>'>
    </label>

    <label>Password:
      <input type='password' name='user[password]' value=''>
    </label>

    <input type="submit" value="Create User!">


</form>